pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
- task: Docker@1
  displayName: 'Build image'
  inputs:
    dockerFile: engine/DOCKERFILE
    command: 'Build an Image'
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'google-lazerfx-website'
    imageName: '$(DockerImageName):$(Build.BuildId)'
- task: Docker@1
  displayName: 'Publish image'
  inputs:
    dockerFile: engine/DOCKERFILE
    command: 'Push an image'
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'google-lazerfx-website'
    imageName: '$(DockerImageName):$(Build.BuildId)'